services:
  postgres:
    image: postgres:13-alpine
    container_name: bytebridge-postgres
    environment:
      POSTGRES_DB: bytebridge
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: bytebridge
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - bytebridge-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d bytebridge"]
      interval: 30s
      timeout: 10s
      retries: 5

  webservice:
    image: ghcr.io/simone-rossi-gb/bytebridge:latest
    container_name: bytebridge
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://bytebridge-postgres:5432/bytebridge
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: bytebridge
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_SHOW_SQL: true
      SERVER_ADDRESS: 0.0.0.0
      SERVER_PORT: 8080
      APP_UPLOAD_DIR: /app/uploads
      CHROME_PATH: /usr/bin/google-chrome
      JAVA_OPTS: -Xmx4096m -Djava.security.egd=file:/dev/./urandom
      LOGGING_LEVEL_WEBSERVICE: INFO
    volumes:
      - uploads_volume:/app/uploads
      - temp_volume:/app/temp
      - logs_volume:/app/logs
    ports:
      - "8080:8080"
    networks:
      - bytebridge-network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  uploads_volume:
    driver: local
  temp_volume:
    driver: local
  logs_volume:
    driver: local

networks:
  bytebridge-network:
    driver: bridge
